export const subtitles = [
  '',
  'And so went my day.',
  'So, I feel like the noose around my neck is getting tighter and tighter.',
  'I\'m tired of thinking about things and doing things.',
  'Tired.',
  '',
  'Wait here.',
  '',
  '',
  '',
  '',
  'In some situations, the only way out is to wait.<br>And all we have is this moment.',
  'Even when it feels like the last circle of hell<br>somehow I feel like if there\'s something to wait for, you won\'t drown in it.',
  'It\'s like an aqualung.<br>There you are underwater and it feels like there\'s almost nothing left to breathe.<br>But you get a few gulps from up there.',
  'I guess I would call it an aspiration, or a goal.<br>As long as you have purpose, you\'ll live.<br>And it\'s not hope, and it\'s not a fruitless search for happiness.',
  'To hell with happiness, those who seek it are the most unhappy people.<br>...<br>You know why I think you can do it?',
  'Because you\'re not going for a fruitless pursuit of happiness.',
  'And someday you\'re gonna surface and breathe.<br>And while you\'re waiting, you\'re gonna start looking around for something to do.<br>And maybe you\'ll even find yourself wondering... who knows.',
  'And you won\'t be waiting alone.<br>You can share your waiting with others,<br>who want to share the moment when you can take off the scuba tank.',
  'Look, the fireflies are on.',
  ''
]
